//
//  SimulationInteractor.swift
//  EasynvestSimulator
//
//  Created by João Gabriel on 15/12/18.
//  Copyright (c) 2018 João Gabriel de Britto e Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulationBusinessLogic
{
  func doSomething(request: Simulation.Something.Request)
}

protocol SimulationDataStore
{
  //var name: String { get set }
}

class SimulationInteractor: SimulationBusinessLogic, SimulationDataStore
{
  var presenter: SimulationPresentationLogic?
  var worker: SimulationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Simulation.Something.Request)
  {
    worker = SimulationWorker()
    worker?.doSomeWork()
    
    let response = Simulation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
