//
//  SimulationViewController.swift
//  EasynvestSimulator
//
//  Created by João Gabriel on 15/12/18.
//  Copyright (c) 2018 João Gabriel de Britto e Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulationDisplayLogic: class
{
  func displaySomething(viewModel: Simulation.Something.ViewModel)
}

class SimulationViewController: UIViewController, SimulationDisplayLogic
{
  var interactor: SimulationBusinessLogic?
  var router: (NSObjectProtocol & SimulationRoutingLogic & SimulationDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SimulationInteractor()
    let presenter = SimulationPresenter()
    let router = SimulationRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
    @IBAction func simulateAgain(_ sender: Any) {
        performSegue(withIdentifier: "unwindToFormVC", sender: self)
    }
    //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Simulation.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Simulation.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
