//
//  SimulationPresenter.swift
//  EasynvestSimulator
//
//  Created by João Gabriel on 15/12/18.
//  Copyright (c) 2018 João Gabriel de Britto e Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SimulationPresentationLogic
{
  func presentSomething(response: Simulation.Something.Response)
}

class SimulationPresenter: SimulationPresentationLogic
{
  weak var viewController: SimulationDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Simulation.Something.Response)
  {
    let viewModel = Simulation.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
