//
//  FormRouter.swift
//  EasynvestSimulator
//
//  Created by João Gabriel on 14/12/18.
//  Copyright (c) 2018 João Gabriel de Britto e Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FormRoutingLogic {
    func routeToSimulationResult(segue: UIStoryboardSegue?)
}

protocol FormDataPassing {
    var dataStore: FormDataStore? { get }
}

class FormRouter: NSObject, FormRoutingLogic, FormDataPassing {
    weak var viewController: FormViewController?
    var dataStore: FormDataStore?
    
    func routeToSimulationResult(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
//            let destinationVC = segue.destination as! SimulationViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SimulationViewController") as! SimulationViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    func navigateToSomewhere(source: FormViewController, destination: SimulationViewController) {
        source.show(destination, sender: nil)
    }
    
    func passDataToSomewhere(source: FormDataStore, destination: inout SimulationViewController) {
//        destination.name = source.name
    }
}
