//
//  FormRouter.swift
//  EasynvestSimulator
//
//  Created by João Gabriel on 14/12/18.
//  Copyright © 2018 João Gabriel de Britto e Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormRoutingLogic {
    func routeToSimulationResult(viewModel: Form.ViewModel)
}

protocol FormDataPassing {
    var dataStore: FormDataStore? { get }
}

class FormRouter: NSObject, FormRoutingLogic, FormDataPassing {
    weak var viewController: FormViewController?
    var dataStore: FormDataStore?

    func routeToSimulationResult(viewModel: Form.ViewModel) {
        guard let destinationVC = viewController?.storyboard?
            .instantiateViewController(withIdentifier: "SimulationViewController") as? SimulationViewController else {
                return
        }

        destinationVC.simulation = viewModel
        if let viewController = self.viewController {
            navigateToSimulationDetail(source: viewController, destination: destinationVC)
        }
    }

    func navigateToSimulationDetail(source: FormViewController, destination: SimulationViewController) {
        source.show(destination, sender: nil)
    }
}
