//
//  FormInteractor.swift
//  EasynvestSimulator
//
//  Created by João Gabriel on 14/12/18.
//  Copyright (c) 2018 João Gabriel de Britto e Silva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FormBusinessLogic {
    func simulateInvestment(with request: Form.Request)
}

protocol FormDataStore {
    //var name: String { get set }
}

class FormInteractor: FormBusinessLogic, FormDataStore {
    var presenter: FormPresentationLogic?
    var worker: FormWorker?
    //var name: String = ""
    
    func simulateInvestment(with request: Form.Request)
    {
        worker = FormWorker()
        
        worker?.simulate(with: request, success: { (response) in
            self.presenter?.presentSimulation(response: response)
        }, fail: { (message) in
            self.presenter?.presentErrorAlert(message: message)
        })
    }
}
